# Requires GoReleaser Pro
includes:
  - from_file:
      path: ./.goreleaser-template.yaml

project_name: chainlink-data-streams

monorepo:
  tag_prefix: chainlink-data-streams@
  dir: chainlink-data-streams