language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- make install-dev
script:
- make lint coverage
deploy:
  provider: pypi
  user: adeptex
  password:
    secure: N9cjMZF20W4zz/zooxvgIppiSRkYh2iGX5uU+nRU1Qr2pPLRl3bESsSWQzp30dfo8V2wphcBUmfQqT+2lOIDz36N4ssWs/x4IHYNUajLHla+QEvyObwEWqYgcnIrl3cqiFtn/LRySA4QHQ0JFib7reD1H2fDyHOURB6S1kFetptovKaJH68W73DfcsdovjehSkybw1gAxpY3ko9GTRPwP1dfRkbFtzH2Jnld5nKLrKuaZ4txl0Dxwn6L+eFL9ZGVsW+wXfv+UkASkNEu5MnXSpD3MZhARuNDA20VVI/OoTjYsoM+KLTkSAFjNano5GfAoGgolc3FEDyeu5LGQcjUlYFkQVdcJtM/XRR8E1XvuAfgD1iY6TA9w/KNhUPR2tNRkotMuvzH2hZIsnbIGn/zmLrUc6RBn7hGZKmJpa7J/McTS7jocF3M+/psh+5qjf68eQsx06xjDkuG9UIi1AvlozjNSuqspGc9yJB43mBAGj8kJRdyAJZ6tUEKsi6QZfAfgnqLd2troFobZ6lekrRp328ZIfLi/JDEY0XRAMGI6m67OruqolW+Gu9+m/hYdufsx4xQGzI1TT5PsoUXLF0dE1TfGXGQye4+WIy7ch2KPLcqH+l7V7XYlEad6WRQE0dBHEmy29KhHW1Wee222QdX01ICE+HTj3Uuvv0JNykeeaU=
  on:
    repo: Skyscanner/whispers
