name: 'PR Labeler'
description: 'Apply labels to your PR based on the title and/or commit messages'
author: 'Grafana'
inputs:
  configuration-path:
    required: false
    description: 'Path to configurations'
    default: '.github/pr-labeler.yml'
  token:
    required: true
    description: 'GitHub access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
