version: 2.1
jobs:
  build_test_push:
    docker:
      - image: mozilla/cidockerbases:docker-latest
    working_directory: /
    environment:
      APP_NAME: "socorro_collector"
    steps:
      - run:
          name: Host info
          command: uname -v

      - run:
          name: Install essential packages
          command: apt-get install make

      - checkout:
          path: /antenna

      - run:
          name: Create version.json
          working_directory: /antenna
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > /antenna/version.json

      - store_artifacts:
          path: /antenna/version.json

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Get info
          command: |
            docker info
            which docker-compose
            docker-compose --version

      - run:
          name: Build Docker image
          working_directory: /antenna
          command: |
            make build

      - run:
          name: Verify requirements.txt file
          working_directory: /antenna
          command: |
            docker run local/antenna_deploy_base shell ./bin/run_verify_reqs.sh

      - run:
          name: Lint
          working_directory: /antenna
          command: |
            docker run local/antenna_deploy_base shell ./docker/run_lint.sh

      - run:
          name: Run tests
          working_directory: /antenna
          command: |
            make test-ci

      - run:
          name: Push to Dockerhub
          working_directory: /antenna
          command: |
            function retry {
                set +e
                local n=0
                local max=3
                while true; do
                "$@" && break || {
                  if [[ $n -lt $max ]]; then
                    ((n++))
                    echo "Command failed. Attempt $n/$max:"
                  else
                    echo "Failed after $n attempts."
                    exit 1
                  fi
                }
                done
                set -e
            }

            # tag images with SHA1 hash or git tag
            export DOCKER_IMAGE="mozilla/${APP_NAME}:${CIRCLE_SHA1}"
            if [ -n "${CIRCLE_TAG}" ]; then
                export DOCKER_IMAGE="mozilla/${APP_NAME}:${CIRCLE_TAG}"
            fi

            # push on main or git tag
            if [ "${CIRCLE_BRANCH}" == "main" ] || [ -n "${CIRCLE_TAG}" ]; then
                echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
                retry docker tag local/antenna_deploy_base "${DOCKER_IMAGE}"
                retry docker push "${DOCKER_IMAGE}"

                # push `latest` on main only
                if [ "${CIRCLE_BRANCH}" == "main" ]; then
                    retry docker tag local/antenna_deploy_base "mozilla/${APP_NAME}:latest"
                    retry docker push "mozilla/${APP_NAME}:latest"
                fi
            fi

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build_test_push:
    jobs:
      - build_test_push:
          filters:
            tags:
              only: /.*/
