name: Build & release
on:
  push:
    branches:
      - releases/**

jobs:
  build:
    name: Build release version
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.0.0

      - name: Install dependencies
        run: npm install

      - name: Stage modules
        run: git add node_modules -f

      - name: Compile TypeScript into compressed JavaScript
        run: npm run build

      - name: Commit compiler version
        uses: EndBug/add-and-commit@releases/test
        with:
          force: true
          message: "[auto] Add compiled version"
          path: lib
          pattern: "*.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
