name: Docs
on:
  push:
    paths:
      - .all-contributorsrc
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  contributors:
    name: Update contributors badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install

      - run: npm run all-contributors-badge

      - uses: EndBug/add-and-commit@v4.0.0
        with:
          message: "[auto] docs: update contributors badge"
          add: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
