name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 'head', '3.0', '2.7', '2.6', '2.5', '2.4' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake
